# Generated by Django 6.0.3 on 2026-04-23 17:43

import django.db.models.deletion
import src.blog.models
import tinymce.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modify_time', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Title')),
                ('title_uk', models.CharField(max_length=100, null=True, unique=True, verbose_name='Title')),
                ('title_ru', models.CharField(max_length=100, null=True, unique=True, verbose_name='Title')),
                ('body', tinymce.models.HTMLField()),
                ('body_uk', tinymce.models.HTMLField(null=True)),
                ('body_ru', tinymce.models.HTMLField(null=True)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('published', 'Published'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=10)),
                ('meta_title', models.CharField(blank=True, max_length=160, null=True)),
                ('meta_title_uk', models.CharField(blank=True, max_length=160, null=True)),
                ('meta_title_ru', models.CharField(blank=True, max_length=160, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=300, null=True)),
                ('meta_description_uk', models.CharField(blank=True, max_length=300, null=True)),
                ('meta_description_ru', models.CharField(blank=True, max_length=300, null=True)),
                ('og_title', models.CharField(blank=True, max_length=160, null=True)),
                ('og_title_uk', models.CharField(blank=True, max_length=160, null=True)),
                ('og_title_ru', models.CharField(blank=True, max_length=160, null=True)),
                ('og_description', models.CharField(blank=True, max_length=300, null=True)),
                ('og_description_uk', models.CharField(blank=True, max_length=300, null=True)),
                ('og_description_ru', models.CharField(blank=True, max_length=300, null=True)),
                ('indexation', models.BooleanField(default=False)),
                ('video_to_post', models.CharField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blog',
                'db_table_comment': 'Blog table',
                'get_latest_by': 'created_at',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modify_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('name_uk', models.CharField(max_length=50, null=True, unique=True)),
                ('name_ru', models.CharField(max_length=50, null=True, unique=True)),
                ('slug', models.SlugField(blank=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=src.blog.models.article_image_upload_path)),
                ('alt', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.article')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.category'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='articles', to='blog.tag'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['-created_at'], name='article_created_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['status', '-created_at'], name='article_status_created_idx'),
        ),
    ]
