# Generated by Django 6.0.3 on 2026-03-30 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='indexation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('pe', 'Pending'), ('pu', 'Published'), ('re', 'Rejected')], default='pe', max_length=2),
        ),
    ]
