# Generated by Django 6.0.3 on 2026-04-23 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_category_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='last_modify_time',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='last_modify_time',
            new_name='updated_at',
        ),
    ]
