# Generated by Django 6.0.3 on 2026-03-30 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='last_modify_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='last_modify_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
