# Generated by Django 6.0.3 on 2026-03-31 13:46

import src.blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_article_meta_description_article_meta_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default=1, upload_to=src.blog.models.article_image_upload_path),
            preserve_default=False,
        ),
    ]
