# Generated by Django 6.0.3 on 2026-03-31 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_article_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
    ]
