# Generated by Django 6.0.3 on 2026-03-31 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_articleimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleimage',
            name='title',
        ),
        migrations.AlterField(
            model_name='articleimage',
            name='alt',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
