# Generated by Django 6.0.3 on 2026-03-31 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_article_meta_title_en_article_meta_title_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='meta_title_en',
        ),
        migrations.RemoveField(
            model_name='article',
            name='title_en',
        ),
    ]
