# Generated by Django 6.0.3 on 2026-03-31 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_remove_article_meta_title_en_remove_article_title_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='meta_description_ru',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='meta_description_uk',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='og_description_ru',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='og_description_uk',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='og_title_ru',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='og_title_uk',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
    ]
