# Generated by Django 6.0.3 on 2026-04-01 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_article_meta_description_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleimage',
            name='caption',
        ),
    ]
