# Generated by Django 6.0.3 on 2026-04-01 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_remove_articleimage_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleimage',
            name='alt_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='articleimage',
            name='alt_uk',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
