# Generated by Django 6.0.3 on 2026-04-01 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_articleimage_alt_ru_articleimage_alt_uk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleimage',
            name='alt_ru',
        ),
        migrations.RemoveField(
            model_name='articleimage',
            name='alt_uk',
        ),
    ]
