# Generated by Django 6.0.3 on 2026-04-03 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_category_name_ru_category_name_uk'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='video_to_post',
            field=models.CharField(blank=True, null=True),
        ),
    ]
