# Generated by Django 6.0.3 on 2026-04-07 16:55

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_article_video_to_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'get_latest_by': 'created_at', 'verbose_name': 'Blog', 'verbose_name_plural': 'Blog'},
        ),
        migrations.AlterModelTableComment(
            name='article',
            table_comment='Blog table',
        ),
        migrations.AddField(
            model_name='article',
            name='body',
            field=tinymce.models.HTMLField(default=2),
            preserve_default=False,
        ),
    ]
