# Generated by Django 6.0.3 on 2026-04-07 17:47

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_alter_article_options_alter_article_table_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='body_ru',
            field=tinymce.models.HTMLField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='body_uk',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
